In [2]:
import pandas as pd
df = pd.read_csv("students_adaptability_level_online_education.csv",sep=",")
df

Education Level Institution Type  Gender  Age  Device IT Student  \
0         University          Private    Male   23     Tab         No   
1         University          Private  Female   23  Mobile         No   
2            College           Public  Female   18  Mobile         No   
3             School          Private  Female   11  Mobile         No   
4             School          Private  Female   18  Mobile         No   
...              ...              ...     ...  ...     ...        ...   
1200         College          Private  Female   18  Mobile         No   
1201         College          Private  Female   18  Mobile         No   
1202          School          Private    Male   11  Mobile         No   
1203         College          Private  Female   18  Mobile         No   
1204          School          Private  Female   11  Mobile         No   

     Location Financial Condition Internet Type Network Type Flexibility Level  
0        Town                 Mid          Wifi           4G          Moderate  
1        Town                 Mid   Mobile Data           4G          Moderate  
2        Town                 Mid          Wifi           4G          Moderate  
3        Town                 Mid   Mobile Data           4G          Moderate  
4        Town                Poor   Mobile Data           3G               Low  
...       ...                 ...           ...          ...               ...  
1200     Town                 Mid          Wifi           4G               Low  
1201    Rural                 Mid          Wifi           4G          Moderate  
1202     Town                 Mid   Mobile Data           3G          Moderate  
1203    Rural                 Mid          Wifi           4G               Low  
1204     Town                Poor   Mobile Data           3G          Moderate  

[1205 rows x 11 columns]

preprocessing techniques

1 - Check missing “NA” :

In [3]:
missing_values = df.isna().sum()
print("\nTotal number of missing values in the dataset:", missing_values.sum())


Total number of missing values in the dataset: 0


2 -Detect Outlier using mean method :

In [12]:

age_column = df['Age']
mean_age = age_column.mean()
differences_from_mean = abs(age_column - mean_age)

# Find the index of the row with the largest difference from the mean
max_difference_index = differences_from_mean.idxmax()

# Remove the row with the largest difference from the mean
df_no_outlier = df.drop(max_difference_index)


print("\nDataFrame after removing the row with the largest difference from the mean:")
df_no_outlier



DataFrame after removing the row with the largest difference from the mean:


Education Level Institution Type  Gender  Age  Device IT Student  \
0         University          Private    Male   23     Tab         No   
1         University          Private  Female   23  Mobile         No   
2            College           Public  Female   18  Mobile         No   
3             School          Private  Female   11  Mobile         No   
4             School          Private  Female   18  Mobile         No   
...              ...              ...     ...  ...     ...        ...   
1200         College          Private  Female   18  Mobile         No   
1201         College          Private  Female   18  Mobile         No   
1202          School          Private    Male   11  Mobile         No   
1203         College          Private  Female   18  Mobile         No   
1204          School          Private  Female   11  Mobile         No   

     Location Financial Condition Internet Type Network Type Flexibility Level  
0        Town                 Mid          Wifi           4G          Moderate  
1        Town                 Mid   Mobile Data           4G          Moderate  
2        Town                 Mid          Wifi           4G          Moderate  
3        Town                 Mid   Mobile Data           4G          Moderate  
4        Town                Poor   Mobile Data           3G               Low  
...       ...                 ...           ...          ...               ...  
1200     Town                 Mid          Wifi           4G               Low  
1201    Rural                 Mid          Wifi           4G          Moderate  
1202     Town                 Mid   Mobile Data           3G          Moderate  
1203    Rural                 Mid          Wifi           4G               Low  
1204     Town                Poor   Mobile Data           3G          Moderate  

[1204 rows x 11 columns]

3 -variable transformation: 

In [16]:
from sklearn.preprocessing import LabelEncoder
from scipy import stats
le = LabelEncoder()
df['Flexibility Level'] = le. fit_transform(df['Flexibility Level'] )
df['Education Level'] = le. fit_transform(df['Education Level'])
df['Gender'] = le. fit_transform(df['Gender'])
df['Location'] = le. fit_transform(df['Location'])   
df['Internet Type'] = le. fit_transform(df['Internet Type']  ) 
df

Education Level Institution Type  Gender  Age  Device IT Student  \
0                   2          Private       1   23     Tab         No   
1                   2          Private       0   23  Mobile         No   
2                   0           Public       0   18  Mobile         No   
3                   1          Private       0   11  Mobile         No   
4                   1          Private       0   18  Mobile         No   
...               ...              ...     ...  ...     ...        ...   
1200                0          Private       0   18  Mobile         No   
1201                0          Private       0   18  Mobile         No   
1202                1          Private       1   11  Mobile         No   
1203                0          Private       0   18  Mobile         No   
1204                1          Private       0   11  Mobile         No   

      Location Financial Condition  Internet Type Network Type  \
0            1                 Mid              1           4G   
1            1                 Mid              0           4G   
2            1                 Mid              1           4G   
3            1                 Mid              0           4G   
4            1                Poor              0           3G   
...        ...                 ...            ...          ...   
1200         1                 Mid              1           4G   
1201         0                 Mid              1           4G   
1202         1                 Mid              0           3G   
1203         0                 Mid              1           4G   
1204         1                Poor              0           3G   

      Flexibility Level  
0                     2  
1                     2  
2                     2  
3                     2  
4                     1  
...                 ...  
1200                  1  
1201                  2  
1202                  2  
1203                  1  
1204                  2  

[1205 rows x 11 columns]

4 -Normalization :

In [19]:
from sklearn.preprocessing import MinMaxScaler

# Extract columns to normalize
columns_to_normalize = ['Age']
data_to_normalize = df[columns_to_normalize]

# Min-Max scaling for selected columns
minmax_scaler = MinMaxScaler()
normalized_data_minmax = minmax_scaler.fit_transform(data_to_normalize)

# Replace the normalized values in the original DataFrame
df[columns_to_normalize] = normalized_data_minmax

print("Min-Max scaled data :")
df

Min-Max scaled data :


Education Level Institution Type  Gender       Age  Device IT Student  \
0                   2          Private       1  0.777778     Tab         No   
1                   2          Private       0  0.777778  Mobile         No   
2                   0           Public       0  0.500000  Mobile         No   
3                   1          Private       0  0.111111  Mobile         No   
4                   1          Private       0  0.500000  Mobile         No   
...               ...              ...     ...       ...     ...        ...   
1200                0          Private       0  0.500000  Mobile         No   
1201                0          Private       0  0.500000  Mobile         No   
1202                1          Private       1  0.111111  Mobile         No   
1203                0          Private       0  0.500000  Mobile         No   
1204                1          Private       0  0.111111  Mobile         No   

      Location Financial Condition  Internet Type Network Type  \
0            1                 Mid              1           4G   
1            1                 Mid              0           4G   
2            1                 Mid              1           4G   
3            1                 Mid              0           4G   
4            1                Poor              0           3G   
...        ...                 ...            ...          ...   
1200         1                 Mid              1           4G   
1201         0                 Mid              1           4G   
1202         1                 Mid              0           3G   
1203         0                 Mid              1           4G   
1204         1                Poor              0           3G   

      Flexibility Level  
0                     2  
1                     2  
2                     2  
3                     2  
4                     1  
...                 ...  
1200                  1  
1201                  2  
1202                  2  
1203                  1  
1204                  2  

[1205 rows x 11 columns]

5 -Discretization :

In [25]:
import pandas as pd
df = pd.read_csv("students_adaptability_level_online_education.csv",sep=",")
# Discretization for a specific column ('Age')
column_to_discretize = 'Age'
num_bins = 3 # Number of bins

# Perform discretization using the cut function
df['discretized_' + column_to_discretize] = pd.cut(df[column_to_discretize], bins=num_bins, labels=False)

df[['Age', 'discretized_Age']] # Displaying relevant columns

Age  discretized_Age
0      23                2
1      23                2
2      18                1
3      11                0
4      18                1
...   ...              ...
1200   18                1
1201   18                1
1202   11                0
1203   18                1
1204   11                0

[1205 rows x 2 columns]

6 -Chi squared :

In [37]:
from scipy.stats import chi2_contingency
import pandas as pd
df = pd.read_csv("students_adaptability_level_online_education.csv",sep=",")
# Create a contingency table
contingency_table = pd.crosstab(df['Flexibility Level'], df['Education Level'])
print("Contingency Table:")
print(contingency_table)
# Perform the chi-square test
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
print("\nChi-Square Statistic:", chi2_stat)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:")
print(expected)

Contingency Table:
Education Level    College  School  University
Flexibility Level                             
High                     3      47          50
Low                    120     182         178
Moderate                96     301         228

Chi-Square Statistic: 38.68597806832386
Degrees of Freedom: 4
Expected Frequencies:
[[ 18.17427386  43.98340249  37.84232365]
 [ 87.23651452 211.12033195 181.64315353]
 [113.58921162 274.89626556 236.51452282]]


7 -Feature selection - Recursive Feature Elimination

In [56]:
import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder

# Load the dataset using pandas
data = pd.read_csv('students_adaptability_level_online_education.csv')

# Identify categorical columns
categorical_columns = ['Flexibility Level', 'Education Level']

# One-hot encode categorical columns
encoder = OneHotEncoder()
X_encoded = encoder.fit_transform(data[categorical_columns])

# Define target variable
y = data['Flexibility Level']  # Assuming 'Flexibility Level' is the target variable

# Use RFE with Logistic Regression as the underlying model
model = LogisticRegression()
rfe = RFE(model, n_features_to_select=2)  # Select top 2 features
X_new = rfe.fit_transform(X_encoded, y)

# Display the selected features
selected_features = [i for i, mask in enumerate(rfe.support_) if mask]
print("Selected Features:", selected_features)



Selected Features: [1, 2]


8 -Feature selection - Correlation-based Feature Selection (Filter Method)

In [62]:
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import OneHotEncoder

# Load the dataset using pandas
data = pd.read_csv('students_adaptability_level_online_education.csv')

# Identify categorical columns
categorical_columns = ['Flexibility Level', 'Education Level']

# One-hot encode categorical columns
encoder = OneHotEncoder()
X_encoded = encoder.fit_transform(data[categorical_columns])

# Define target variable
y = data['Flexibility Level']  # Assuming 'Flexibility Level' is the target variable

# Convert the sparse matrix into a dense array
X_dense = X_encoded.toarray()

# Use SelectKBest with f_classif as the scoring function
selector = SelectKBest(score_func=f_classif, k=2) # Select top 2 features
X_new = selector.fit_transform(X_dense, y)

# Display the selected features
selected_features = data.columns[selector.get_support(indices=True)]
print("Selected Features:", selected_features)


Selected Features: Index(['Institution Type', 'Gender'], dtype='object')


9 -Correlation Coefficient : we dont have 2 types of numerical attribute

statistical summaries :

In [67]:
import pandas as pd
df = pd.read_csv("students_adaptability_level_online_education.csv",sep=",")
df.describe()


Age
count  1205.000000
mean     17.065560
std       5.830369
min       9.000000
25%      11.000000
50%      18.000000
75%      23.000000
max      27.000000

In [68]:
var_data = df["Age"] . var()
print(var_data)

33.993206600405294


In [74]:
import numpy as np
from scipy.stats import mode
import pandas as pd
df = pd.read_csv("students_adaptability_level_online_education.csv",sep=",")
# Median
median_value = df["Age"].median()
print("Median:", median_value)

# Mode

mode_result = df["Age"].mode()
print("Mode:", mode_result)

Median: 18.0
Mode: 0    23
Name: Age, dtype: int64
